# -*- coding: utf-8 -*-
"""Predicting heart disease using Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uuZw6u35A3-oGD1Gl553CAllUg8Yocwl

#Predicting heart disease using Machine Learning

#This project is a binary classification problem as it takes the data and classifies it into Yes/No values
"""

#Thid is where you'll get different information about each of the features in your data.
#Create data dictinorys

import sklearn
sklearn.__version__

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import RocCurveDisplay

df = pd.read_csv('heart-disease.csv')
df.shape

df.head()

df.tail()

df['target'].value_counts()

df['target'].value_counts().plot(kind="pie")

df.info()

df.describe()

df.sex.value_counts()

#comparing target with other columsn
pd.crosstab(df.target,df.sex)

pd.crosstab(df.target,df.sex).plot(kind="bar")
plt.title("Heat disease")
plt.xlabel("Tatgets")
plt.ylabel("Poeple")
plt.legend(["Male","Female"])

df['thalach']

plt.figure(figsize=(10,6))
plt.scatter(df.age[df.target==1],
            df.thalach[df.target==1],
            c="orange")

plt.scatter(df.age[df.target==0],
            df.thalach[df.target==0])

plt.figure(figsize=(10,6))
plt.scatter(df.age[df.target==1],
            df.thalach[df.target==1],
            c="orange")
plt.scatter(df.age[df.target==0],
            df.thalach[df.target==0])
plt.title("Heart disease in age and max heart rate")
plt.xlabel("Age")
plt.ylabel("Max heart rate")
plt.legend(["Disease","No disease"])

df.age.plot.hist()
#to find the distribution

pd.crosstab(df.cp,df.target)

pd.crosstab(df.cp,df.target).plot()
plt.title("Heart Disease Frequency per chest pain type")
plt.xlabel("Chest pain type")
plt.ylabel("Amount")
plt.legend(["No disease","disease"])

df.head()

df.corr()

corr_matrix = df.corr()
fig,ax = plt.subplots(figsize=(15,10))
ax=sns.heatmap(corr_matrix,
               fmt=".2f",
               annot=True,
               linewidths=0.5,
               cmap="YlGnBu")

X = df.drop('target',axis=1)
Y = df["target"]

X

Y

np.random.seed(42)
X_train, X_test ,y_train,y_test=train_test_split(X,Y,test_size=0.2)

X_train

y_train

models={"Logistic Regression":LogisticRegression(),
        "KNN": KNeighborsClassifier(),
        "Random Forest": RandomForestClassifier()}

def fit_and_score(models,X_train,X_test,y_train,y_test):
  np.random.seed(42)
  model_scores={}
  for name, model in models.items():
    model.fit(X_train,y_train)
    model_scores[name]=model.score(X_test,y_test)
  return model_scores

model_scores = fit_and_score(models=models,
                             X_train=X_train,
                             y_train=y_train,
                             X_test=X_test,
                             y_test=y_test)

model_scores

model_compare = pd.DataFrame(model_scores ,index=["accuracy"])
model_compare.T.plot.bar();
# t is used because it is we need to transpose it so we can understand it better

#we will do hyperparameter tuning and feature impotance confusiion matric
train_scores = []
test_scores = []

neighbors = range(1, 21)
knn = KNeighborsClassifier()

for i in neighbors:
    knn.set_params(n_neighbors=i)

    knn.fit(X_train, y_train)

    train_scores.append(knn.score(X_train, y_train))
    test_scores.append(knn.score(X_test, y_test))

#it will give best scores and best values so when we put in grpah we will understand better
plt.plot(neighbors, train_scores, label="Train Scores")
plt.plot(neighbors, test_scores, label="Test Scores")

plt.xlabel("Number of neighbors")
plt.ylabel("Model scores")

plt.xticks(range(1, 21, 1))
plt.legend()

plt.show()
#even after getting betterment of knn model ...its worse than other two so we will discard this model

log_reg_grid = {"C": np.logspace(-4,4,20),
                "solver": ["liblinear"]}

rf_grid={"n_estimators": np.arange(10,1000,10),
         "max_depth":[None,3,5,10],
         "min_samples_split":np.arange(2,20,2),
         "min_samples_leaf":np.arange(1,20,2)}

np.random.seed(42)
rs_log_res= RandomizedSearchCV(LogisticRegression(),
                               param_distributions=log_reg_grid,
                               cv=5,
                               n_iter=20,
                               verbose=True)

rs_log_res.fit(X_train, y_train)

rs_log_res.best_params_

rs_log_res.score(X_test,y_test)

np.random.seed(42)
rs_rf=RandomizedSearchCV(RandomForestClassifier(),
                         param_distributions=rf_grid,
                         cv=5,
                         n_iter=20,
                         verbose=True)
rs_rf.fit(X_train, y_train)

rs_rf.best_estimator_

rs_rf.score(X_test, y_test)

model_scores

log_reg_grid = {
    "C": np.logspace(-4, 4, 30),
    "solver": ["liblinear"]
}

gs_log_reg = GridSearchCV(
    LogisticRegression(),
    param_grid=log_reg_grid,
    cv=5,
    verbose=1
)

gs_log_reg.fit(X_train, y_train)

gs_log_reg.best_params_

#plotting the roc curve and calculate the auc metric
RocCurveDisplay.from_estimator(gs_log_reg, X_test, y_test)

y_preds=gs_log_reg.predict(X_test)
print(confusion_matrix(y_test,y_preds))

sns.set(font_scale=1.5)
def plot_conf_mat(y_test,y_preds):
  fig, ax=plt.subplots(figsize=(3,3))
  ax=sns.heatmap(confusion_matrix(y_test,y_preds),
                 annot=True,
                 cbar=False)
  plt.xlabel("True label")
  plt.ylabel("Predicted label")
plot_conf_mat(y_test,y_preds)

print(classification_report(y_test,y_preds))

gs_log_reg.best_params_

clf = LogisticRegression(C=0.20433597178569418,
                         solver="liblinear")

cv_acc=cross_val_score(clf,X,Y,cv=5,scoring="accuracy")
cv_acc

cv_acc=np.mean(cv_acc)

cv_precision=cross_val_score(clf,X,Y,cv=5,scoring="precision")
cv_precision=np.mean(cv_precision)
cv_precision

cv_recall=cross_val_score(clf,X,Y,cv=5,scoring="recall")
cv_recall=np.mean(cv_recall)
cv_recall

cv_f1=cross_val_score(clf,X,Y,cv=5,scoring="f1")
cv_f1=np.mean(cv_f1)
cv_f1

cv_metrics=pd.DataFrame({"Accuracy":cv_acc,
                         "Precision":cv_precision,
                         "Recall":cv_recall,
                         "F1":cv_f1},
                        index=[0])

cv_metrics.T.plot.bar(title="Cross-validated classification metrics",
                      legend=False)

clf = LogisticRegression(C=0.20433597178569418,
                         solver="liblinear")
clf.fit(X_train,y_train)

clf.coef_

feature_dict= dict(zip(df.columns, list(clf.coef_[0])))
feature_dict

feature_df=pd.DataFrame(feature_dict, index=[0])
feature_df.T.plot.bar(title="Feature Importance",legend=False);

pd.crosstab(df["slope"],df["target"])