# -*- coding: utf-8 -*-
"""Regression Coding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWTBXcIbDG9jO2IaGrqALpRD8pVyI55z
"""

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

print(f"pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")
print(f"matplotlib version: {matplotlib.__version__}")

from pathlib import Path

dataset_dir = Path("../data/bluebook-for-bulldozers")
if not (dataset_dir.is_dir()):
    print(f"[INFO] Can't find existing 'bluebook-for-bulldozers' dataset in current directory or parent directory, downloading...")
    !wget https://github.com/mrdbourke/zero-to-mastery-ml/raw/refs/heads/master/data/bluebook-for-bulldozers.zip
    !unzip bluebook-for-bulldozers.zip
    !mkdir ../data/
    !mv bluebook-for-bulldozers ../data/
    print(f"[INFO] Current dataset dir: {dataset_dir}")
    !rm -rf bluebook-for-bulldozers.zip
else:
    print(f"[INFO] 'bluebook-for-bulldozers' dataset exists, feel free to proceed!")
    print(f"[INFO] Current dataset dir: {dataset_dir}")

import os

print(f"[INFO] Files/folders available in {dataset_dir}:")
os.listdir(dataset_dir)

df = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/TrainAndValid.csv")

df.info()

df["saledate"][:10]

fig, ax = plt.subplots()
ax.scatter(x=df["saledate"][:1000],
           y=df["SalePrice"][:1000])
ax.set_xlabel("Sale Date")
ax.set_ylabel("Sale Price ($)");

df.SalePrice.plot.hist(xlabel="Sale Price ($)");

df = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/TrainAndValid.csv",
                 low_memory=False,
                 parse_dates=["saledate"])


df.info()

df["saledate"][:10]

fig, ax = plt.subplots()
ax.scatter(x=df["saledate"][:1000],
           y=df["SalePrice"][:1000])
ax.set_xlabel("Sale Date")
ax.set_ylabel("Sale Price ($)");

df.sort_values(by=["saledate"], inplace=True, ascending=True)
df.saledate.head(10), df.saledate.tail(10)

df_tmp = df.copy()

df_tmp["saleYear"] = df_tmp.saledate.dt.year
df_tmp["saleMonth"] = df_tmp.saledate.dt.month
df_tmp["saleDay"] = df_tmp.saledate.dt.day
df_tmp["saleDayofweek"] = df_tmp.saledate.dt.dayofweek
df_tmp["saleDayofyear"] = df_tmp.saledate.dt.dayofyear

df_tmp.drop("saledate", axis=1, inplace=True)

df_tmp[["SalePrice", "saleYear", "saleMonth", "saleDay", "saleDayofweek", "saleDayofyear"]].head()

fig, ax = plt.subplots()
ax.scatter(x=df_tmp["saleMonth"][:10000],
           y=df_tmp["SalePrice"][:10000])
ax.set_xlabel("Sale Month")
ax.set_ylabel("Sale Price ($)");

df_tmp.groupby(["saleMonth"])["SalePrice"].median().plot()
plt.xlabel("Month")
plt.ylabel("Median Sale Price ($)");

df_tmp.state.value_counts()[:10]

median_prices_by_state = df_tmp.groupby(["state"])["SalePrice"].median()
median_sale_price = df_tmp["SalePrice"].median()

plt.figure(figsize=(10, 7))
plt.bar(x=median_prices_by_state.index,
        height=median_prices_by_state.values)
plt.xlabel("State")
plt.ylabel("Median Sale Price ($)")
plt.xticks(rotation=90, fontsize=7);
plt.axhline(y=median_sale_price,
            color="red",
            linestyle="--",
            label=f"Median Sale Price: ${median_sale_price:,.0f}")
plt.legend();

df_tmp.info();

df_tmp.head().isna()

df_tmp.isna().sum()

df_tmp["UsageBand"].dtype, df_tmp["UsageBand"].dtype.name

pd.api.types.is_object_dtype(df_tmp["UsageBand"])

pd.api.types.is_string_dtype(df_tmp["state"])

random_dict = {"key1": "hello",
               "key2": "world!"}

for key, value in random_dict.items():
    print(f"This is a key: {key}")
    print(f"This is a value: {value}")

for label, content in df_tmp.items():
    if pd.api.types.is_string_dtype(content):
        column_datatype = df_tmp[label].dtype.name
        example_value = content.sample(1).values
        example_value_dtype = pd.api.types.infer_dtype(example_value)
        print(f"Column name: {label} | Column dtype: {column_datatype} | Example value: {example_value} | Example value dtype: {example_value_dtype}")

number_of_object_type_columns = 0

for label, content in df_tmp.items():
    if pd.api.types.is_object_dtype(content):
        column_datatype = df_tmp[label].dtype.name
        example_value = content.sample(1).values
        example_value_dtype = pd.api.types.infer_dtype(example_value)
        print(f"Column name: {label} | Column dtype: {column_datatype} | Example value: {example_value} | Example value dtype: {example_value_dtype}")

        number_of_object_type_columns += 1

print(f"\n[INFO] Total number of object type columns: {number_of_object_type_columns}")

for label, content in df_tmp.items():
    if pd.api.types.is_object_dtype(content):
        df_tmp[label] = df_tmp[label].astype("category")

df_tmp.info()

df_tmp.state.dtype

df_tmp.state.cat.categories

df_tmp.state.cat.codes

target_state_cat_number = 43
target_state_cat_value = df_tmp.state.cat.categories[target_state_cat_number]
print(f"[INFO] Target state category number {target_state_cat_number} maps to: {target_state_cat_value}")

df_tmp.to_csv("../data/bluebook-for-bulldozers/TrainAndValid_object_values_as_categories.csv",
              index=False)

df_tmp = pd.read_csv("../data/bluebook-for-bulldozers/TrainAndValid_object_values_as_categories.csv",
                     low_memory=False)

df_tmp.head()

df_tmp.info()

for label, content in df_tmp.items():
    if pd.api.types.is_object_dtype(content):
        df_tmp[label] = df_tmp[label].astype("category")

df_tmp.to_parquet(path="../data/bluebook-for-bulldozers/TrainAndValid_object_values_as_categories.parquet",
                  engine="auto")

df_tmp = pd.read_parquet(path="../data/bluebook-for-bulldozers/TrainAndValid_object_values_as_categories.parquet",
                         engine="auto")
df_tmp.info()

df_tmp.isna().sum().sort_values(ascending=False)[:20]

for label, content in df_tmp.items():
    if pd.api.types.is_numeric_dtype(content):
        column_datatype = df_tmp[label].dtype.name
        example_value = content.sample(1).values
        example_value_dtype = pd.api.types.infer_dtype(example_value)
        print(f"Column name: {label} | Column dtype: {column_datatype} | Example value: {example_value} | Example value dtype: {example_value_dtype}")

for label, content in df_tmp.items():
    if pd.api.types.is_numeric_dtype(content):
        if pd.isnull(content).sum():
            print(f"Column name: {label} | Has missing values: {True}")
        else:
            print(f"Column name: {label} | Has missing values: {False}")

for label, content in df_tmp.items():
    if pd.api.types.is_numeric_dtype(content):
        if pd.isnull(content).sum():
            df_tmp[label+"_is_missing"] = pd.isnull(content).astype(int)
            df_tmp[label] = content.fillna(content.median())

df_tmp[df_tmp["MachineHoursCurrentMeter_is_missing"] == 1].sample(5)

for label, content in df_tmp.items():
    if pd.api.types.is_numeric_dtype(content):
        if pd.isnull(content).sum():
            print(f"Column name: {label} | Has missing values: {True}")
        else:
            print(f"Column name: {label} | Has missing values: {False}")

df_tmp.auctioneerID_is_missing.value_counts()

print(f"[INFO] Columns which are not numeric:")
for label, content in df_tmp.items():
    if not pd.api.types.is_numeric_dtype(content):
        print(f"Column name: {label} | Column dtype: {df_tmp[label].dtype.name}")

column_to_category_dict = {}
for label, content in df_tmp.items():
    if not pd.api.types.is_numeric_dtype(content):
        df_tmp[label+"_is_missing"] = pd.isnull(content).astype(int)
        content_categories = pd.Categorical(content)
        content_category_codes = content_categories.codes + 1


        column_to_category_dict[label] = dict(zip(content_category_codes, content_categories))

        df_tmp[label] = content_category_codes

df_tmp.sample(5)

for key, value in sorted(column_to_category_dict["UsageBand"].items()):
    print(f"{key} -> {value}")

for key, value in sorted(column_to_category_dict["state"].items())[:10]:
    print(f"{key} -> {value}")

total_missing_values = df_tmp.isna().sum().sum()

if total_missing_values == 0:
    print(f"[INFO] Total missing values: {total_missing_values} - Woohoo! Let's build a model!")
else:
    print(f"[INFO] Uh ohh... total missing values: {total_missing_values} - Perhaps we might have to retrace our steps to fill the values?")

df_tmp.to_parquet(path="../data/bluebook-for-bulldozers/TrainAndValid_object_values_as_categories_and_missing_values_filled.parquet",
                  engine="auto")

df_tmp = pd.read_parquet(path="../data/bluebook-for-bulldozers/TrainAndValid_object_values_as_categories_and_missing_values_filled.parquet",
                         engine="auto")

total_missing_values = df_tmp.isna().sum().sum()

if total_missing_values == 0:
    print(f"[INFO] Total missing values: {total_missing_values} - Woohoo! Let's build a model!")
else:
    print(f"[INFO] Uh ohh... total missing values: {total_missing_values} - Perhaps we might have to retrace our steps to fill the values?")

# Commented out IPython magic to ensure Python compatibility.
# %%time
# df_tmp_sample_1k = df_tmp.sample(n=1000, random_state=42)
# model = RandomForestRegressor(n_jobs=-1)
# X_sample_1k = df_tmp_sample_1k.drop("SalePrice", axis=1)
# y_sample_1k = df_tmp_sample_1k["SalePrice"]
# model.fit(X=X_sample_1k,
#           y=y_sample_1k)

model_sample_1k_score = model.score(X=X_sample_1k,
                                    y=y_sample_1k)

print(f"[INFO] Model score on {len(df_tmp_sample_1k)} samples: {model_sample_1k_score}")

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# model = RandomForestRegressor(n_jobs=-1)
# X_all = df_tmp.drop("SalePrice", axis=1)
# y_all = df_tmp["SalePrice"]
# model.fit(X=X_all,
#           y=y_all)

model_sample_all_score = model.score(X=X_all,
                                     y=y_all)

print(f"[INFO] Model score on {len(df_tmp)} samples: {model_sample_all_score}")

train_df = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/Train.csv",
                       parse_dates=["saledate"],
                       low_memory=False).sort_values(by="saledate", ascending=True)
valid_df = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/Valid.csv",
                       parse_dates=["saledate"])
valid_solution = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/ValidSolution.csv")
valid_df["SalePrice"] = valid_df["SalesID"].map(valid_solution.set_index("SalesID")["SalePrice"])
valid_df = valid_df.sort_values("saledate", ascending=True).reset_index(drop=True)
print(f"[INFO] Number of samples in training DataFrame: {len(train_df)}")
print(f"[INFO] Number of samples in validation DataFrame: {len(valid_df)}")

train_df.sample(5)

valid_df.sample(5)

def add_datetime_features_to_df(df, date_column="saledate"):
    df["saleYear"] = df[date_column].dt.year
    df["saleMonth"] = df[date_column].dt.month
    df["saleDay"] = df[date_column].dt.day
    df["saleDayofweek"] = df[date_column].dt.dayofweek
    df["saleDayofyear"] = df[date_column].dt.dayofyear
    df.drop("saledate", axis=1, inplace=True)

    return df

train_df = add_datetime_features_to_df(df=train_df)
valid_df = add_datetime_features_to_df(df=valid_df)

train_df.iloc[:, -5:].sample(5)

numerical_features = [label for label, content in X_train.items() if pd.api.types.is_numeric_dtype(content)]
categorical_features = [label for label, content in X_train.items() if not pd.api.types.is_numeric_dtype(content)]

print(f"[INFO] Numeric features: {numerical_features}")
print(f"[INFO] Categorical features: {categorical_features[:10]}...")

from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder(categories="auto",
                                 handle_unknown="use_encoded_value",
                                 unknown_value=np.nan,
                                 encoded_missing_value=np.nan)

X_train_preprocessed = X_train.copy()
X_train_preprocessed[categorical_features] = ordinal_encoder.fit_transform(X_train_preprocessed[categorical_features].astype(str))
X_valid_preprocessed = X_valid.copy()
X_valid_preprocessed[categorical_features] = ordinal_encoder.transform(X_valid_preprocessed[categorical_features].astype(str))

X_train.head()

X_train_preprocessed.head()

X_train[categorical_features].isna().sum().sort_values(ascending=False)[:10]

X_train_preprocessed[categorical_features].isna().sum().sort_values(ascending=False)[:10]

ordinal_encoder.categories_[:3]

column_to_category_mapping = {}

for column_name, category_values in zip(categorical_features, ordinal_encoder.categories_):
    int_to_category = {i: category for i, category in enumerate(category_values)}
    column_to_category_mapping[column_name] = int_to_category
column_to_category_mapping["UsageBand"]

X_train_unprocessed = X_train_preprocessed[categorical_features].copy()
X_train_unprocessed = ordinal_encoder.inverse_transform(X_train_unprocessed)
X_train_unprocessed_df = pd.DataFrame(X_train_unprocessed, columns=categorical_features)
X_train_unprocessed_df.sample(5)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# model = RandomForestRegressor(n_jobs=-1)
# model.fit(X=X_train_preprocessed,
#           y=y_train)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# model.score(X=X_valid_preprocessed,
#             y=y_valid)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# model.score(X=X_train_preprocessed,
#             y=y_train)

from sklearn.metrics import mean_absolute_error, root_mean_squared_log_error
def show_scores(model,
                train_features=X_train_preprocessed,
                train_labels=y_train,
                valid_features=X_valid_preprocessed,
                valid_labels=y_valid):
    train_preds = model.predict(X=train_features)
    val_preds = model.predict(X=valid_features)

    scores = {"Training MAE": mean_absolute_error(y_true=train_labels,
                                                  y_pred=train_preds),
              "Valid MAE": mean_absolute_error(y_true=valid_labels,
                                               y_pred=val_preds),
              "Training RMSLE": root_mean_squared_log_error(y_true=train_labels,
                                                            y_pred=train_preds),
              "Valid RMSLE": root_mean_squared_log_error(y_true=valid_labels,
                                                         y_pred=val_preds),
              "Training R^2": model.score(X=train_features,
                                          y=train_labels),
              "Valid R^2": model.score(X=valid_features,
                                       y=valid_labels)}
    return scores

model_scores = show_scores(model=model)
model_scores

# Commented out IPython magic to ensure Python compatibility.
# %%time
# model = RandomForestRegressor(n_estimators=100,
#                               n_jobs=-1,
#                               max_samples=10000)
# model.fit(X_train_preprocessed,
#           y_train)

base_model_scores = show_scores(model=model)
base_model_scores

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# from sklearn.model_selection import RandomizedSearchCV
# rf_grid = {"n_estimators": np.arange(10, 200, 10),
#            "max_depth": [None, 10, 20],
#            "min_samples_split": np.arange(2, 10, 1),
#            "max_features": [0.5, 1.0, "sqrt"],
#            "max_samples": [10000]}
# 
# rs_model = RandomizedSearchCV(estimator=RandomForestRegressor(),
#                               param_distributions=rf_grid,
#                               n_iter=20,
#                               verbose=3)
# rs_model.fit(X=X_train_preprocessed,
#              y=y_train)

rs_model.best_params_

rs_model_scores = show_scores(rs_model)
rs_model_scores

# Commented out IPython magic to ensure Python compatibility.
# %%time
# ideal_model = RandomForestRegressor(n_estimators=90,
#                                     max_depth=None,
#                                     min_samples_leaf=1,
#                                     min_samples_split=5,
#                                     max_features=0.5,
#                                     n_jobs=-1,
#                                     max_samples=None)
# ideal_model.fit(X=X_train_preprocessed,
#                 y=y_train)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# ideal_model_scores = show_scores(model=ideal_model)
# ideal_model_scores

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# fast_model = RandomForestRegressor(n_estimators=45,
#                                    max_depth=None,
#                                    min_samples_leaf=1,
#                                    min_samples_split=5,
#                                    max_features=0.5,
#                                    n_jobs=-1,
#                                    max_samples=None)
# 
# fast_model.fit(X=X_train_preprocessed,
#                y=y_train)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# fast_model_scores = show_scores(model=fast_model)
# fast_model_scores

base_model_scores["model_name"] = "default_model"
rs_model_scores["model_name"] = "random_search_model"
ideal_model_scores["model_name"] = "ideal_model"
fast_model_scores["model_name"] = "fast_model"
all_model_scores = [base_model_scores,
                    rs_model_scores,
                    ideal_model_scores,
                    fast_model_scores]
model_comparison_df = pd.DataFrame(all_model_scores).sort_values(by="Valid RMSLE", ascending=False)
model_comparison_df.head()

mean_rsmle_score = model_comparison_df["Valid RMSLE"].mean()
plt.figure(figsize=(10, 5))
plt.bar(x=model_comparison_df["model_name"],
        height=model_comparison_df["Valid RMSLE"].values)
plt.xlabel("Model")
plt.ylabel("Validation RMSLE (lower is better)")
plt.xticks(rotation=0, fontsize=10);
plt.axhline(y=mean_rsmle_score,
            color="red",
            linestyle="--",
            label=f"Mean RMSLE: {mean_rsmle_score:.4f}")
plt.legend();

import joblib
bulldozer_price_prediction_model_name = "randomforest_regressor_best_RMSLE.pkl"
joblib.dump(value=ideal_model,
            filename=bulldozer_price_prediction_model_name)

best_model = joblib.load(filename=bulldozer_price_prediction_model_name)
best_model

best_model_scores = show_scores(model=best_model)
best_model_scores

best_model_scores["Valid RMSLE"] == ideal_model_scores["Valid RMSLE"]

if np.isclose(a=best_model_scores["Valid RMSLE"],
              b=ideal_model_scores["Valid RMSLE"],
              atol=1e-4):
    print(f"[INFO] Model results are close!")
else:
    print(f"[INFO] Model results aren't close, did something go wrong?")

test_df = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/Test.csv",
                      parse_dates=["saledate"])
test_df.head()

def add_datetime_features_to_df(df, date_column="saledate"):
    df["saleYear"] = df[date_column].dt.year
    df["saleMonth"] = df[date_column].dt.month
    df["saleDay"] = df[date_column].dt.day
    df["saleDayofweek"] = df[date_column].dt.dayofweek
    df["saleDayofyear"] = df[date_column].dt.dayofyear
    df.drop("saledate", axis=1, inplace=True)
    return df
test_df = add_datetime_features_to_df(df=test_df)
test_df.head()

test_df_preprocessed = test_df.copy()
test_df_preprocessed[categorical_features] = ordinal_encoder.transform(test_df_preprocessed[categorical_features].astype(str))
test_df_preprocessed.info()

test_preds = best_model.predict(test_df_preprocessed)

test_preds[:10]

test_preds.shape, test_df.shape

pred_df = pd.DataFrame()
pred_df["SalesID"] = test_df["SalesID"]
pred_df["SalePrice"] = test_preds
pred_df.sample(5)

pred_df.to_csv("../data/bluebook-for-bulldozers/predictions.csv",
               index=False)

test_df_preprocessed_sample = test_df_preprocessed.sample(n=1, random_state=42)
test_df_unpreprocessed_sample = test_df_preprocessed_sample.copy()
test_df_unpreprocessed_sample[categorical_features] = ordinal_encoder.inverse_transform(test_df_unpreprocessed_sample[categorical_features])
test_df_unpreprocessed_sample.to_dict(orient="records")

best_model.predict(test_df_preprocessed_sample)

custom_sample = {
  "SalesID": np.nan,
  "MachineID": 8504,
  "ModelID": np.nan,
  "datasource": np.nan,
  "auctioneerID": np.nan,
  "YearMade": 2004,
  "MachineHoursCurrentMeter": 11770.0,
  "UsageBand": "High",
  "fiModelDesc": "D6RXL",
  "fiBaseModel": "D6",
  "fiSecondaryDesc": "XL",
  "fiModelSeries": np.nan,
  "fiModelDescriptor": np.nan,
  "ProductSize": "Medium",
  "fiProductClassDesc": "Track Type Tractor, Dozer - 130.0 to 160.0 Horsepower",
  "state": "Missouri",
  "ProductGroup": "TTT",
  "ProductGroupDesc": "Track Type Tractors",
  "Drive_System": "No",
  "Enclosure": "EROPS",
  "Forks": "None or Unspecified",
  "Pad_Type": "Grouser",
  "Ride_Control": "None or Unspecified",
  "Stick": "nan",
  "Transmission": "Powershift",
  "Turbocharged": "None or Unspecified",
  "Blade_Extension": "None or Unspecified",
  "Blade_Width": np.nan,
  "Enclosure_Type": np.nan,
  "Engine_Horsepower": np.nan,
  "Hydraulics": np.nan,
  "Pushblock": "None or Unspecified",
  "Ripper": "None or Unspecified",
  "Scarifier": "None or Unspecified",
  "Tip_Control": "Tip",
  "Tire_Size": np.nan,
  "Coupler": np.nan,
  "Coupler_System": np.nan,
  "Grouser_Tracks": "Yes",
  "Hydraulics_Flow": np.nan,
  "Track_Type": "Steel",
  "Undercarriage_Pad_Width": "22 inch",
  "Stick_Length": np.nan,
  "Thumb": np.nan,
  "Pattern_Changer": np.nan,
  "Grouser_Type": "Single",
  "Backhoe_Mounting": "None or Unspecified",
  "Blade_Type": "Semi U",
  "Travel_Controls": np.nan,
  "Differential_Type": np.nan,
  "Steering_Controls": "Command Control",
  "saleYear": 2024,
  "saleMonth": 6,
  "saleDay": 7,
  "saleDayofweek": 5,
  "saleDayofyear": 159
}

custom_sample_df = pd.DataFrame(custom_sample, index=[0])
custom_sample_df.head()

custom_sample_df[categorical_features] = ordinal_encoder.transform(custom_sample_df[categorical_features].astype(str))
custom_sample_df

custom_sample_pred = best_model.predict(custom_sample_df)
print(f"[INFO] Predicted sale price of custom sample: ${round(custom_sample_pred[0], 2)}")

from sklearn.metrics import mean_absolute_error, root_mean_squared_log_error
custom_sample_actual_sale_price = [72600]

print(f"[INFO] Model MAE on custom sample: {mean_absolute_error(y_pred=custom_sample_pred, y_true=custom_sample_actual_sale_price)}")
print(f"[INFO] Model RMSLE on custom sample: {root_mean_squared_log_error(y_pred=custom_sample_pred, y_true=custom_sample_actual_sale_price)}")

best_model_feature_importances = best_model.feature_importances_
best_model_feature_importances

print(f"[INFO] Number of feature importance values: {best_model_feature_importances.shape[0]}")
print(f"[INFO] Number of features in training dataset: {X_train_preprocessed.shape[1]}")

column_names = test_df.columns
feature_importance_df = pd.DataFrame({"feature_names": column_names,
                                      "feature_importance": best_model_feature_importances}).sort_values(by="feature_importance",
                                                                                                         ascending=False)
feature_importance_df.head()

top_n = 20
plt.figure(figsize=(10, 5))
plt.barh(y=feature_importance_df["feature_names"][:top_n],
         width=feature_importance_df["feature_importance"][:top_n])
plt.title(f"Top {top_n} Feature Importance Values for Best RandomForestRegressor Model")
plt.xlabel("Feature importance value")
plt.ylabel("Feature name")
plt.gca().invert_yaxis();

print(f"[INFO] Unique ProductSize values: {train_df['ProductSize'].unique()}")
print(f"[INFO] Unique Enclosure values: {train_df['Enclosure'].unique()}")

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import mean_absolute_error, root_mean_squared_log_error
from sklearn.ensemble import RandomForestRegressor
train_df = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/Train.csv",
                       parse_dates=["saledate"],
                       low_memory=False).sort_values(by="saledate", ascending=True)

valid_df = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/Valid.csv",
                       parse_dates=["saledate"])

valid_solution = pd.read_csv(filepath_or_buffer="../data/bluebook-for-bulldozers/ValidSolution.csv")

valid_df["SalePrice"] = valid_df["SalesID"].map(valid_solution.set_index("SalesID")["SalePrice"])

valid_df = valid_df.sort_values("saledate", ascending=True).reset_index(drop=True)

print(f"[INFO] Number of samples in training DataFrame: {len(train_df)}")
print(f"[INFO] Number of samples in validation DataFrame: {len(valid_df)}")

def add_datetime_features_to_df(df, date_column="saledate"):
    df["saleYear"] = df[date_column].dt.year
    df["saleMonth"] = df[date_column].dt.month
    df["saleDay"] = df[date_column].dt.day
    df["saleDayofweek"] = df[date_column].dt.dayofweek
    df["saleDayofyear"] = df[date_column].dt.dayofyear
    df.drop("saledate", axis=1, inplace=True)

    return df
train_df = add_datetime_features_to_df(df=train_df)
valid_df = add_datetime_features_to_df(df=valid_df)
X_train = train_df.drop("SalePrice", axis=1)
y_train = train_df["SalePrice"]
X_valid = valid_df.drop("SalePrice", axis=1)
y_valid = valid_df["SalePrice"]
numeric_features = [label for label, content in X_train.items() if pd.api.types.is_numeric_dtype(content)]
categorical_features = [label for label, content in X_train.items() if not pd.api.types.is_numeric_dtype(content)]
ordinal_encoder = OrdinalEncoder(categories="auto",
                                 handle_unknown="use_encoded_value",
                                 unknown_value=np.nan,
                                 encoded_missing_value=np.nan)

simple_imputer_median = SimpleImputer(missing_values=np.nan,
                                      strategy="median")


X_train_preprocessed = X_train.copy()
X_train_preprocessed[categorical_features] = ordinal_encoder.fit_transform(X_train_preprocessed[categorical_features].astype(str))
X_train_preprocessed[numerical_features] = simple_imputer_median.fit_transform(X_train_preprocessed[numerical_features])
X_valid_preprocessed = X_valid.copy()
X_valid_preprocessed[categorical_features] = ordinal_encoder.transform(X_valid_preprocessed[categorical_features].astype(str))
X_valid_preprocessed[numerical_features] = simple_imputer_median.transform(X_valid_preprocessed[numerical_features])
def show_scores(model,
                train_features=X_train_preprocessed,
                train_labels=y_train,
                valid_features=X_valid_preprocessed,
                valid_labels=y_valid):
    train_preds = model.predict(X=train_features)
    val_preds = model.predict(X=valid_features)
    scores = {"Training MAE": mean_absolute_error(y_true=train_labels,
                                                  y_pred=train_preds),
              "Valid MAE": mean_absolute_error(y_true=valid_labels,
                                               y_pred=val_preds),
              "Training RMSLE": root_mean_squared_log_error(y_true=train_labels,
                                                            y_pred=train_preds),
              "Valid RMSLE": root_mean_squared_log_error(y_true=valid_labels,
                                                         y_pred=val_preds),
              "Training R^2": model.score(X=train_features,
                                          y=train_labels),
              "Valid R^2": model.score(X=valid_features,
                                       y=valid_labels)}
    return scores
ideal_model_2 = RandomForestRegressor(n_estimators=90,
                                      max_depth=None,
                                      min_samples_leaf=1,
                                      min_samples_split=5,
                                      max_features=0.5,
                                      n_jobs=-1,
                                      max_samples=None)

ideal_model_2.fit(X=X_train_preprocessed,
                  y=y_train)
ideal_model_2_scores = show_scores(model=ideal_model_2)
ideal_model_2_scores

import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, root_mean_squared_log_error
from sklearn.preprocessing import OrdinalEncoder, FunctionTransformer
from sklearn.pipeline import Pipeline

train_df = pd.read_csv("../data/bluebook-for-bulldozers/Train.csv",
                       parse_dates=["saledate"],
                       low_memory=False).sort_values(by="saledate", ascending=True)

valid_df = pd.read_csv("../data/bluebook-for-bulldozers/Valid.csv",
                       parse_dates=["saledate"])

valid_solution = pd.read_csv("../data/bluebook-for-bulldozers/ValidSolution.csv")
valid_df["SalePrice"] = valid_df["SalesID"].map(valid_solution.set_index("SalesID")["SalePrice"])
valid_df = valid_df.sort_values("saledate", ascending=True).reset_index(drop=True)

def add_datetime_features_to_df(df, date_column="saledate"):
    df = df.copy()
    df["saleYear"] = df[date_column].dt.year
    df["saleMonth"] = df[date_column].dt.month
    df["saleDay"] = df[date_column].dt.day
    df["saleDayofweek"] = df[date_column].dt.dayofweek
    df["saleDayofyear"] = df[date_column].dt.dayofyear
    return df.drop(date_column, axis=1)

train_df = add_datetime_features_to_df(train_df)
valid_df = add_datetime_features_to_df(valid_df)
X_train = train_df.drop("SalePrice", axis=1)
y_train = train_df["SalePrice"]
X_valid = valid_df.drop("SalePrice", axis=1)
y_valid = valid_df["SalePrice"]

numeric_features = [label for label, content in X_train.items()
                   if pd.api.types.is_numeric_dtype(content)]
categorical_features = [label for label, content in X_train.items()
                       if not pd.api.types.is_numeric_dtype(content)]

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_transformer = Pipeline(steps=[
    ('string_converter', FunctionTransformer(lambda x: x.astype(str))),
    ('ordinal', OrdinalEncoder(handle_unknown='use_encoded_value',
                              unknown_value=np.nan,
                              encoded_missing_value=np.nan)),
])

preprocessor = ColumnTransformer(
    transformers=[
        ('numerical_transforms', numeric_transformer, numeric_features),
        ('categorical_transforms', categorical_transformer, categorical_features)
    ])

model_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(
        n_estimators=90,
        max_depth=None,
        min_samples_leaf=1,
        min_samples_split=5,
        max_features=0.5,
        n_jobs=-1,
        max_samples=None
    ))
])

def evaluate_pipeline(pipeline, X_train, y_train, X_valid, y_valid):
    train_preds = pipeline.predict(X_train)
    valid_preds = pipeline.predict(X_valid)
    scores = {
        "Training MAE": mean_absolute_error(y_train, train_preds),
        "Valid MAE": mean_absolute_error(y_valid, valid_preds),
        "Training RMSLE": root_mean_squared_log_error(y_train, train_preds),
        "Valid RMSLE": root_mean_squared_log_error(y_valid, valid_preds),
        "Training R^2": pipeline.score(X_train, y_train),
        "Valid R^2": pipeline.score(X_valid, y_valid)
    }
    return scores
model_pipeline.fit(X_train, y_train)
pipeline_scores = evaluate_pipeline(model_pipeline, X_train, y_train, X_valid, y_valid)
print("\nPipeline Scores:")
pipeline_scores

import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, root_mean_squared_log_error
from sklearn.preprocessing import OrdinalEncoder, FunctionTransformer, StandardScaler
from sklearn.pipeline import Pipeline


train_df = pd.read_csv("../data/bluebook-for-bulldozers/Train.csv",
                       parse_dates=["saledate"],
                       low_memory=False).sort_values(by="saledate", ascending=True)

valid_df = pd.read_csv("../data/bluebook-for-bulldozers/Valid.csv",
                       parse_dates=["saledate"])

valid_solution = pd.read_csv("../data/bluebook-for-bulldozers/ValidSolution.csv")
valid_df["SalePrice"] = valid_df["SalesID"].map(valid_solution.set_index("SalesID")["SalePrice"])
valid_df = valid_df.sort_values("saledate", ascending=True).reset_index(drop=True)

def add_datetime_features_to_df(df, date_column="saledate"):
    df = df.copy()
    df["saleYear"] = df[date_column].dt.year
    df["saleMonth"] = df[date_column].dt.month
    df["saleDay"] = df[date_column].dt.day
    df["saleDayofweek"] = df[date_column].dt.dayofweek
    df["saleDayofyear"] = df[date_column].dt.dayofyear
    return df.drop(date_column, axis=1)


train_df = add_datetime_features_to_df(train_df)
valid_df = add_datetime_features_to_df(valid_df)
X_train = train_df.drop("SalePrice", axis=1)
y_train = train_df["SalePrice"]
X_valid = valid_df.drop("SalePrice", axis=1)
y_valid = valid_df["SalePrice"]

numeric_features = [label for label, content in X_train.items()
                   if pd.api.types.is_numeric_dtype(content)]
categorical_features = [label for label, content in X_train.items()
                       if not pd.api.types.is_numeric_dtype(content)]

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
])

categorical_transformer = Pipeline(steps=[
    ('string_converter', FunctionTransformer(lambda x: x.astype(str))),
    ('ordinal', OrdinalEncoder(categories='auto',
                               handle_unknown='use_encoded_value',
                               unknown_value=np.nan,
                               encoded_missing_value=np.nan)),
])

preprocessor = ColumnTransformer(
    transformers=[
        ('numerical_transforms', numeric_transformer, numeric_features),
        ('categorical_transforms', categorical_transformer, categorical_features)
    ])

model_pipeline_hist_gradient_boosting_regressor = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', HistGradientBoostingRegressor())
])

def evaluate_pipeline(pipeline, X_train, y_train, X_valid, y_valid):

    train_preds = pipeline.predict(X_train)
    valid_preds = pipeline.predict(X_valid)

    scores = {
        "Training MAE": mean_absolute_error(y_train, train_preds),
        "Valid MAE": mean_absolute_error(y_valid, valid_preds),
        "Training RMSLE": root_mean_squared_log_error(y_train, train_preds),
        "Valid RMSLE": root_mean_squared_log_error(y_valid, valid_preds),
        "Training R^2": pipeline.score(X_train, y_train),
        "Valid R^2": pipeline.score(X_valid, y_valid)
    }
    return scores

print(f"[INFO] Fitting HistGradientBoostingRegressor model with pipeline...")
model_pipeline_hist_gradient_boosting_regressor.fit(X_train, y_train)
print(f"[INFO] Evaluating HistGradientBoostingRegressor model with pipeline...")
pipeline_hist_scores = evaluate_pipeline(model_pipeline_hist_gradient_boosting_regressor, X_train, y_train, X_valid, y_valid)
print("\nPipeline HistGradientBoostingRegressor Scores:")
pipeline_hist_scores

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# import pandas as pd
# import numpy as np
# from sklearn.impute import SimpleImputer
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.metrics import mean_absolute_error, root_mean_squared_log_error
# from sklearn.pipeline import Pipeline
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import FunctionTransformer
# train_df = pd.read_csv("../data/bluebook-for-bulldozers/Train.csv",
#                        parse_dates=["saledate"],
#                        low_memory=False).sort_values(by="saledate", ascending=True)
# 
# valid_df = pd.read_csv("../data/bluebook-for-bulldozers/Valid.csv",
#                        parse_dates=["saledate"])
# 
# valid_solution = pd.read_csv("../data/bluebook-for-bulldozers/ValidSolution.csv")
# valid_df["SalePrice"] = valid_df["SalesID"].map(valid_solution.set_index("SalesID")["SalePrice"])
# valid_df = valid_df.sort_values("saledate", ascending=True).reset_index(drop=True)
# def add_datetime_features_to_df(df, date_column="saledate"):
#     df = df.copy()
#     df["saleYear"] = df[date_column].dt.year
#     df["saleMonth"] = df[date_column].dt.month
#     df["saleDay"] = df[date_column].dt.day
#     df["saleDayofweek"] = df[date_column].dt.dayofweek
#     df["saleDayofyear"] = df[date_column].dt.dayofyear
#     return df.drop(date_column, axis=1)
# 
# train_df = add_datetime_features_to_df(train_df)
# valid_df = add_datetime_features_to_df(valid_df)
# 
# X_train = train_df.drop("SalePrice", axis=1)
# y_train = train_df["SalePrice"]
# X_valid = valid_df.drop("SalePrice", axis=1)
# y_valid = valid_df["SalePrice"]
# 
# numeric_features = [label for label, content in X_train.items()
#                    if pd.api.types.is_numeric_dtype(content)]
# categorical_features = [label for label, content in X_train.items()
#                        if not pd.api.types.is_numeric_dtype(content)]
# 
# 
# numeric_transformer = Pipeline(steps=[
#     ('imputer', SimpleImputer(strategy='median'))
# ])
# 
# categorical_transformer = Pipeline(steps=[
#     ('string_converter', FunctionTransformer(lambda x: x.astype(str))),
#     ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
#     ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=True))
# ])
# 
# 
# preprocessor = ColumnTransformer(
#     transformers=[
#         ('num', numeric_transformer, numeric_features),
#         ('cat', categorical_transformer, categorical_features)
#     ],
#     verbose_feature_names_out=False
# )
# 
# model_one_hot_pipeline = Pipeline([
#     ('preprocessor', preprocessor),
#     ('regressor', RandomForestRegressor(
#         n_estimators=10,
#         max_depth=None,
#         min_samples_leaf=1,
#         min_samples_split=5,
#         max_features=0.5,
#         n_jobs=-1,
#         max_samples=None
#     ))
# ])
# 
# def evaluate_pipeline(pipeline, X_train, y_train, X_valid, y_valid):
#     train_preds = pipeline.predict(X_train)
#     valid_preds = pipeline.predict(X_valid)
#     scores = {
#         "Training MAE": mean_absolute_error(y_train, train_preds),
#         "Valid MAE": mean_absolute_error(y_valid, valid_preds),
#         "Training RMSLE": root_mean_squared_log_error(y_train, train_preds),
#         "Valid RMSLE": root_mean_squared_log_error(y_valid, valid_preds),
#         "Training R^2": pipeline.score(X_train, y_train),
#         "Valid R^2": pipeline.score(X_valid, y_valid)
#     }
#     return scores
# print(f"[INFO] Fitting model with one hot encoded values...")
# model_one_hot_pipeline.fit(X_train, y_train)
# print(f"[INFO] Evaluating model with one hot encoded values...")
# pipeline_one_hot_scores = evaluate_pipeline(model_one_hot_pipeline, X_train, y_train, X_valid, y_valid)
# print("[INFO] Pipeline with one hot encoding scores:")
# pipeline_one_hot_scores